# Generated by Django 4.2.1 on 2023-06-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3er', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
    ]
