# Generated by Django 4.2.1 on 2023-06-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3er', '0002_rename_nombre_curso_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
