# Generated by Django 4.2.1 on 2023-06-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3er', '0003_adopcion_delete_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Adoptante',
        ),
    ]
