# Generated by Django 4.2.1 on 2023-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3er', '0004_rename_estudiante_adoptante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
