# Generated by Django 4.2.1 on 2023-06-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3er', '0005_insumo_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
